"""empty message

Revision ID: 560afb7acd6b
Revises: 
Create Date: 2020-12-28 18:52:15.417653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '560afb7acd6b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('media', sa.String(), nullable=True),
    sa.Column('age_limit', sa.String(), nullable=True),
    sa.Column('information', sa.String(), nullable=True),
    sa.Column('friend_stranger', sa.String(), nullable=True),
    sa.Column('policies', sa.String(), nullable=True),
    sa.Column('victim', sa.String(), nullable=True),
    sa.Column('government', sa.String(), nullable=True),
    sa.Column('social_sites', sa.String(), nullable=True),
    sa.Column('parents', sa.String(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('opinion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
